# Generated by Django 4.2.15 on 2024-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestionar_indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
