# Generated by Django 4.2.15 on 2024-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformasTecnologicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('proyecto', models.TextField()),
                ('url', models.TextField()),
                ('alcance', models.TextField()),
            ],
        ),
    ]
