# Generated by Django 4.2.15 on 2024-10-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_plataformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformastecnologicas',
            name='alcance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plataformastecnologicas',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plataformastecnologicas',
            name='proyecto',
            field=models.CharField(max_length=200),
        ),
    ]
