# Generated by Django 4.2.15 on 2024-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_plataformas', '0002_alter_plataformastecnologicas_alcance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlataformasTecnologicas',
            new_name='PlataformaTecnologica',
        ),
    ]
