# Generated by Django 4.2.15 on 2024-11-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_plataformas', '0003_rename_plataformastecnologicas_plataformatecnologica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformatecnologica',
            name='alcance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plataformatecnologica',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plataformatecnologica',
            name='proyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plataformatecnologica',
            name='url',
            field=models.URLField(),
        ),
    ]
