# Generated by Django 4.2.15 on 2024-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_plataformas', '0004_alter_plataformatecnologica_alcance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformatecnologica',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
