# Generated by Django 4.2.15 on 2024-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_plataformas', '0005_plataformatecnologica_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformatecnologica',
            name='alcance',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('provincial', 'Provincial'), ('municipal', 'Municipal')], max_length=255),
        ),
    ]
