# Generated by Django 4.2.15 on 2024-10-31 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_gestion_indicadores', '0007_alter_categoriaanalisis_nombre_and_more'),
        ('app_gestion_plataformas', '0003_rename_plataformastecnologicas_plataformatecnologica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente a evaluar', 'Pendiente a evaluar'), ('pendiente a selección', 'Pendiente a selección'), ('evaluada', 'Evaluada')], default='pendiente a selección', max_length=100)),
                ('objetivo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_plataformas.plataformatecnologica')),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('evaluacionPlataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_evaluaciones.evaluacionplataforma')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.indicador')),
            ],
            options={
                'unique_together': {('evaluacionPlataforma', 'indicador')},
            },
        ),
    ]
