# Generated by Django 4.2.15 on 2024-11-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('evaluacion', models.CharField(choices=[('Sí', 'sí'), ('No', 'no')], max_length=50)),
                ('seleccionIndicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_evaluaciones.seleccionindicador')),
            ],
        ),
    ]
