# Generated by Django 4.2.15 on 2024-10-02 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnalisis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DestinoImpacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.categoriaanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.componente')),
                ('destino_impacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.destinoimpacto')),
            ],
        ),
        migrations.CreateModel(
            name='Subdimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('categoria_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.categoriaanalisis')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.componente')),
                ('destino_impacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.destinoimpacto')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.dimension')),
                ('subdimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.subdimension')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='destino_impacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.destinoimpacto'),
        ),
    ]
