# Generated by Django 4.2.15 on 2024-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaanalisis',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destinoimpacto',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subdimension',
            name='concepto',
            field=models.TextField(null=True),
        ),
    ]
