# Generated by Django 4.2.15 on 2024-10-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0003_remove_indicador_categoria_analisis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='descripcion',
            new_name='concepto',
        ),
    ]
