# Generated by Django 4.2.15 on 2024-10-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0004_rename_descripcion_indicador_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_indicadores.dimension'),
        ),
    ]
