# Generated by Django 4.2.15 on 2024-10-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0005_alter_indicador_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaanalisis',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destinoimpacto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdimension',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
