# Generated by Django 4.2.15 on 2024-10-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0006_categoriaanalisis_habilitado_componente_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaanalisis',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='destinoimpacto',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subdimension',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
