# Generated by Django 4.2.15 on 2024-11-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_indicadores', '0007_alter_categoriaanalisis_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('potencial', 'Potencial'), ('transversal', 'Transversal'), ('real', 'Real')], max_length=50),
        ),
    ]
